-- -----------------------------------------------------
-- DYNAMIC COLORS (Generated by Matugen)
-- -----------------------------------------------------

_G.color_primary = "{{colors.primary.default.hex}}"
_G.color_primary_rgba = "rgba({{colors.primary.default.hex_stripped}}, 0.1)"
_G.color_surface = "{{colors.surface.default.hex}}"

return true
