[config]
# This tells Matugen to create the actual config files from your templates

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.swaync]
input_path = "~/.config/matugen/templates/waybar.css" 
output_path = "~/.config/swaync/colors.css"

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = "~/.config/fuzzel/fuzzel.ini"

[templates.fastfetch_main]
input_path = "~/.config/matugen/templates/config.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.fastfetch_small]
input_path = "~/.config/matugen/templates/small.jsonc"
output_path = "~/.config/fastfetch/small.jsonc"

[templates.nemo]
input_path = "~/.config/matugen/templates/nemo.css"
output_path = "~/.config/gtk-3.0/colors.css"
[templates.hypr_colors_lua]
input_path = "~/.config/matugen/templates/colors.lua"
output_path = "~/.config/hypr/configs/colors.lua"

[templates.fish]
input_path = "~/.config/matugen/templates/colors.fish"
output_path = "~/.config/fish/colors.fish"

[templates.foot]
input_path = "~/.config/matugen/templates/colors.ini"
output_path = "~/.config/foot/colors.ini"

[templates.zsh]
input_path = "~/.config/matugen/templates/colors.zsh"
output_path = "~/.config/zsh/colors.zsh"

[templates.cava]
input_path = "~/.config/matugen/templates/cava.ini"
output_path = "~/.config/cava/themes/matugen"
