-- -----------------------------------------------------
-- DYNAMIC COLORS (Generated by Matugen)
-- -----------------------------------------------------

_G.color_primary = "#b1cbd3"
_G.color_primary_rgba = "rgba(b1cbd3, 0.1)"
_G.color_surface = "#121414"

return true
