source = $HOME/.config/hypr/colors.conf

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot
    color = $surface
    blur_passes = 2
    blur_size = 10
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.4
    vibrancy = 0.2
}

# --- TOP CLOCK ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 0.8)
    font_size = 120
    font_family = Geist Bold
    position = 0, 340
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 5
}

label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 0.7)
    font_size = 22
    font_family = Geist SemiBold
    position = 0, 250
    halign = center
    valign = center
}

# --- ARCH LOGO IMAGE (CENTER WITH SHADOW) ---
image {
    monitor =
    path = $HOME/hyprland/assets/arch_logo.png
    size = 180
    border_size = 0
    rounding = 0
    position = 0, 0
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 10
    shadow_color = rgba(0, 0, 0, 0.5)
}

# --- USER NAME (BOTTOM GROUP) ---
label {
    monitor =
    text = Masum
    color = rgba(255, 255, 255, 0.9)
    font_size = 24
    font_family = Geist SemiBold
    position = 0, 160
    halign = center
    valign = bottom
}

# --- INPUT FIELD (BOTTOM GROUP) ---
input-field {
    monitor =
    size = 280, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = $primary
    check_color = $primary
    fail_color = $error
    fade_on_empty = false
    placeholder_text = <span foreground="##ffffff66">Enter Password</span>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    hide_input = false
    rounding = 25
    position = 0, 80
    halign = center
    valign = bottom
}


# --- CAPS LOCK WARNING (BOTTOM RIGHT) ---
label {
    monitor =
    text = cmd[update:200] echo "$(hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .capsLock' | grep -q true && echo '󰬈  Caps Lock ON')"
    color = $primary
    font_size = 12
    font_family = Geist Bold
    position = -50, 50
    halign = right
    valign = bottom
}

# --- BATTERY ---
label {
    monitor =
    text = cmd[update:1000] echo "<span font_family='GeistMono Nerd Font'>󰁹</span> $(cat /sys/class/power_supply/BAT1/capacity)%"
    color = rgba(255, 255, 255, 0.8)
    font_size = 20
    font_family = Geist
    position = -50, -40
    halign = right
    valign = top
}
