-- -----------------------------------------------------
-- HYPRLAND LUA CONFIGURATION (v0.55+)
-- -----------------------------------------------------
require("configs.colors")
require("configs.env")
require("configs.monitors")
require("configs.settings")
require("configs.binds")
require("configs.autostart")

hl.config({
    autogenerated = false
})

-- 1. Native Persistent Workspaces (Official v0.55.0 Syntax)
-- These must be OUTSIDE of hl.config
for i = 1, 5 do
    hl.workspace_rule({
        workspace = tostring(i),
        persistent = true,
        monitor = "eDP-1",
        default = (i == 1)
    })
end

-- 2. Native Gestures (Official v0.55.0 Syntax)
-- Workspace swipe
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Window swipe
hl.gesture({
    fingers = 4,
    direction = "left",
    action = function()
        hl.dispatch(hl.dsp.exec_cmd("~/.config/hypr/scripts/layout_navigate.sh focus_right"))
    end
})

hl.gesture({
    fingers = 4,
    direction = "right",
    action = function()
        hl.dispatch(hl.dsp.exec_cmd("~/.config/hypr/scripts/layout_navigate.sh focus_left"))
    end
})
